### ISSUE TITLE
ScaffoldMessenger shown under NavBar

### ISSUE THREAD

**Issue by marcoberetta96** [rafalbednarczuk/curved_navigation_bar#100]
ScaffoldMessenger messages are shown under the CurvedNavigationBar and this looks very ugly.
Is there any way to show ScaffoldMessenger messages on the top of the CurvedNavigationBar?
Thanks!

**Comment by rafalbednarczuk** [comment]
It's possible to show the `SnackBar` over `CurvedNavigationBar` by setting `behavior` and `margin`.  
`CurvedNavigationBar` is set that way that it overflows over the `body` of a `Scaffold`, that's why by default the `SnackBar` is under the `CurvedNavigationBar`


```dart
ScaffoldMessenger.of(context).showSnackBar(
  SnackBar(
    behavior:SnackBarBehavior.floating ,
    margin: EdgeInsets.fromLTRB(15.0, 5.0, 15.0, 20.0),
    content: Text("Very important message"),
  ),
);
```

![Simulator Screenshot - iPhone 15 - 2024-06-03 at 11 01 06](https://github.com/rafalbednarczuk/curved_navigation_bar/assets/14034293/99556b4d-a58c-47e0-85db-0e09f49a3812)
__
