### ISSUE TITLE
initial index is not working for me

### ISSUE THREAD

**Issue by ShashankSirmour** [rafalbednarczuk/curved_navigation_bar#2]
i think initial index is not setup in init state that's why it is not set to passed index at initial stage(i try it by hot reload )

**Comment by rafalbednarczuk** [comment]
You are right. Fixed in:
https://github.com/rafalbednarczuk/curved_navigation_bar/commit/16e18b4d18392b71775238a9ffb70f5ac06d155a
Also, remember index param (now initialIndex) is only to set first position when app is started. Changing initialIndex and hot reload won't do anything with CurvedNavigationBar, you have to relaunch app to see effects of initialIndex.
