### ISSUE TITLE
Not able to set backgroundColor to transparent.

### ISSUE THREAD

**Issue by rishabh-deligence** [rafalbednarczuk/curved_navigation_bar#48]

**Comment by demiansolano** [comment]
Same here!

**Comment by demiansolano** [comment]
Just figured out, it is simply a widget so instead of placing it in the bottomNavigationBar of the scaffold, use a Stack and Positioned widget to bring it down to the bottom
the default background for bottomNavigationBar is black and outside of any background image or color you configure your scaffold so you will not see your background color or image.

**Comment by rishabh-deligence** [comment]
It worked Thanks.

**Comment by rafalbednarczuk** [comment]
duplicate of https://github.com/rafalbednarczuk/curved_navigation_bar/issues/31
